import type { AppState, DietaryTag, FamilyMember, InventoryItem, Recipe, StorageZone } from './types'

export const STORAGE_KEY = 'seven-day-food-planner'

export const dietaryOptions: DietaryTag[] = [
  'Vegetarian',
  'Vegan',
  'Pescatarian',
  'Gluten-Free',
  'Dairy-Free',
  'Nut-Free',
  'High-Protein',
  'Low-Sodium',
]

export const days = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
]

export const storageZones: StorageZone[] = ['Cupboard', 'Fridge', 'Freezer']

export const emptyProductForm = {
  name: '',
  quantity: 1,
  unit: 'pack',
  zone: 'Cupboard' as StorageZone,
  expiresOn: '',
}

const starterInventory: InventoryItem[] = [
  {
    id: 'i-1',
    name: 'Chickpeas',
    quantity: 2,
    unit: 'tins',
    zone: 'Cupboard',
    expiresOn: '',
    source: 'manual',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 164, protein: 8.9, fiber: 7.6, fat: 2.6, sugar: 4.8, sodium: 24 },
  },
  {
    id: 'i-2',
    name: 'Frozen mixed vegetables',
    quantity: 1,
    unit: 'bag',
    zone: 'Freezer',
    expiresOn: '',
    source: 'manual',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 70, protein: 3.8, fiber: 4.6, fat: 0.7, sugar: 5.1, sodium: 40 },
  },
  {
    id: 'i-3',
    name: 'Greek yogurt',
    quantity: 500,
    unit: 'g',
    zone: 'Fridge',
    expiresOn: '',
    source: 'manual',
    dietaryTags: ['Vegetarian', 'High-Protein'],
    allergens: ['milk'],
    health: { calories: 97, protein: 9, fiber: 0, fat: 5, sugar: 3.6, sodium: 36 },
  },
]

const starterFamily: FamilyMember[] = [
  {
    id: 'f-1',
    name: 'Alex',
    dietProfile: 'Vegan',
    eatsFish: false,
    dietaryNeeds: ['Nut-Free'] as DietaryTag[],
    avoidIngredients: 'walnuts, peanuts',
  },
  {
    id: 'f-2',
    name: 'Sam',
    dietProfile: 'Omnivore',
    eatsFish: false,
    dietaryNeeds: ['High-Protein'] as DietaryTag[],
    avoidIngredients: '',
  },
]

export const defaultState: AppState = {
  inventory: starterInventory,
  family: starterFamily,
  householdNeeds: ['Nut-Free'],
  cookedMeals: {},
}

export const recipeLibrary: Recipe[] = [
  {
    id: 'r-1',
    title: 'Smoky Chickpea Traybake',
    description: 'Roasted chickpeas and vegetables with paprika, lemon, and herbs.',
    ingredients: ['chickpeas', 'mixed vegetables', 'olive oil', 'paprika', 'lemon'],
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Nut-Free'],
    allergens: [],
    cookTime: 30,
    zoneFocus: ['Cupboard', 'Freezer'],
    nutrition: { calories: 430, protein: 18, fiber: 13, carbs: 48, fat: 14, sodium: 320 },
    healthHighlights: ['High fibre', 'Plant-based protein', 'Good freezer use'],
  },
  {
    id: 'r-2',
    title: 'Herby Yogurt Chicken Bowls',
    description: 'Chicken bowls with yogurt dressing, grains, and crunchy veg.',
    ingredients: ['chicken breast', 'greek yogurt', 'rice', 'cucumber', 'spinach'],
    dietaryTags: ['Gluten-Free', 'High-Protein', 'Nut-Free'],
    allergens: ['milk'],
    cookTime: 35,
    zoneFocus: ['Fridge', 'Cupboard'],
    nutrition: { calories: 520, protein: 39, fiber: 6, carbs: 42, fat: 18, sodium: 410 },
    healthHighlights: ['High protein', 'Balanced carbs', 'Great for packed lunches'],
  },
  {
    id: 'r-3',
    title: 'Freezer Veg Stir-Fry',
    description: 'A quick stir-fry built around freezer vegetables and pantry sauces.',
    ingredients: ['mixed vegetables', 'soy sauce', 'rice noodles', 'garlic', 'tofu'],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free'],
    allergens: ['soy'],
    cookTime: 20,
    zoneFocus: ['Freezer', 'Cupboard'],
    nutrition: { calories: 455, protein: 21, fiber: 8, carbs: 56, fat: 14, sodium: 620 },
    healthHighlights: ['Fast weeknight meal', 'Uses freezer staples', 'Good vegetable density'],
  },
  {
    id: 'r-4',
    title: 'Lentil Cottage Pie',
    description: 'Comforting lentil pie with mashed potato topping and hidden vegetables.',
    ingredients: ['lentils', 'potatoes', 'carrots', 'peas', 'vegetable stock'],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Nut-Free'],
    allergens: ['celery'],
    cookTime: 55,
    zoneFocus: ['Cupboard', 'Freezer', 'Fridge'],
    nutrition: { calories: 470, protein: 19, fiber: 15, carbs: 63, fat: 12, sodium: 360 },
    healthHighlights: ['High fibre', 'Family-friendly', 'Good batch cook'],
  },
  {
    id: 'r-5',
    title: 'Salmon, Greens and New Potatoes',
    description: 'A lighter dinner with omega-3 rich salmon and green vegetables.',
    ingredients: ['salmon', 'potatoes', 'broccoli', 'peas', 'lemon'],
    dietaryTags: ['Pescatarian', 'Gluten-Free', 'High-Protein', 'Nut-Free'],
    allergens: ['fish'],
    cookTime: 28,
    zoneFocus: ['Fridge', 'Freezer'],
    nutrition: { calories: 510, protein: 37, fiber: 9, carbs: 35, fat: 24, sodium: 280 },
    healthHighlights: ['Omega-3 fats', 'High protein', 'Lower sodium'],
  },
  {
    id: 'r-6',
    title: 'Black Bean Chili',
    description: 'Hearty bean chili with tomatoes, peppers, and warming spices.',
    ingredients: ['black beans', 'tomatoes', 'peppers', 'onion', 'cumin'],
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Nut-Free'],
    allergens: [],
    cookTime: 40,
    zoneFocus: ['Cupboard', 'Fridge'],
    nutrition: { calories: 445, protein: 17, fiber: 16, carbs: 58, fat: 11, sodium: 300 },
    healthHighlights: ['High fibre', 'Budget-friendly', 'Great for leftovers'],
  },
  {
    id: 'r-7',
    title: 'Turkey Meatball Orzo Bake',
    description: 'Protein-forward baked orzo with meatballs, tomato, and spinach.',
    ingredients: ['turkey mince', 'orzo', 'tomatoes', 'spinach', 'mozzarella'],
    dietaryTags: ['Nut-Free'],
    allergens: ['milk', 'gluten'],
    cookTime: 45,
    zoneFocus: ['Fridge', 'Cupboard'],
    nutrition: { calories: 560, protein: 34, fiber: 5, carbs: 49, fat: 24, sodium: 540 },
    healthHighlights: ['High protein', 'Oven-to-table', 'Crowd-pleasing'],
  },
  {
    id: 'r-8',
    title: 'Coconut Red Lentil Curry',
    description: 'Creamy lentil curry with spinach and fragrant spices.',
    ingredients: ['red lentils', 'coconut milk', 'spinach', 'onion', 'curry paste'],
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Nut-Free'],
    allergens: [],
    cookTime: 32,
    zoneFocus: ['Cupboard', 'Fridge'],
    nutrition: { calories: 485, protein: 20, fiber: 12, carbs: 51, fat: 19, sodium: 340 },
    healthHighlights: ['Iron-rich greens', 'High fibre', 'Plant-based dinner'],
  },
  {
    id: 'r-9',
    title: 'Sheet-Pan Sausage and Vegetables',
    description: 'Roasted sausages with colourful vegetables for a simple dinner.',
    ingredients: ['sausages', 'potatoes', 'peppers', 'broccoli', 'red onion'],
    dietaryTags: ['Nut-Free'],
    allergens: [],
    cookTime: 38,
    zoneFocus: ['Fridge', 'Freezer'],
    nutrition: { calories: 590, protein: 24, fiber: 8, carbs: 39, fat: 36, sodium: 760 },
    healthHighlights: ['Simple prep', 'Balanced plate', 'Flexible vegetables'],
  },
  {
    id: 'r-10',
    title: 'Yogurt Berry Breakfast Pots',
    description: 'Make-ahead breakfast pots with yogurt, oats, berries, and seeds.',
    ingredients: ['greek yogurt', 'berries', 'oats', 'chia seeds', 'honey'],
    dietaryTags: ['Vegetarian', 'High-Protein', 'Nut-Free'],
    allergens: ['milk', 'gluten'],
    cookTime: 10,
    zoneFocus: ['Fridge', 'Cupboard', 'Freezer'],
    nutrition: { calories: 320, protein: 18, fiber: 7, carbs: 36, fat: 10, sodium: 90 },
    healthHighlights: ['Breakfast prep', 'Protein rich', 'Supports satiety'],
  },
]
