import type { AppState, DietaryTag, FamilyMember, InventoryItem, Recipe, StorageZone } from './types'

export const STORAGE_KEY = 'seven-day-food-planner'

export const dietaryOptions: DietaryTag[] = [
  'Vegetarian',
  'Vegan',
  'Pescatarian',
  'Gluten-Free',
  'Dairy-Free',
  'Nut-Free',
  'High-Protein',
  'Low-Sodium',
]

export const days = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
]

export const storageZones: StorageZone[] = ['Cupboard', 'Fridge', 'Freezer']

export const emptyProductForm = {
  name: '',
  quantity: 1,
  unit: 'pack',
  zone: 'Cupboard' as StorageZone,
  expiresOn: '',
}

const starterInventory: InventoryItem[] = [
  {
    id: 'i-1',
    name: 'Chickpeas',
    brand: '',
    categories: ['Legumes', 'Tinned goods'],
    quantity: 2,
    unit: 'tins',
    zone: 'Cupboard',
    expiresOn: '',
    source: 'manual',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 164, protein: 8.9, fiber: 7.6, fat: 2.6, sugar: 4.8, sodium: 24 },
  },
  {
    id: 'i-2',
    name: 'Frozen mixed vegetables',
    brand: '',
    categories: ['Vegetables', 'Frozen'],
    quantity: 1,
    unit: 'bag',
    zone: 'Freezer',
    expiresOn: '',
    source: 'manual',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 70, protein: 3.8, fiber: 4.6, fat: 0.7, sugar: 5.1, sodium: 40 },
  },
  {
    id: 'i-3',
    name: 'Greek yogurt',
    brand: '',
    categories: ['Dairy', 'Yogurt'],
    quantity: 500,
    unit: 'g',
    zone: 'Fridge',
    expiresOn: '',
    source: 'manual',
    dietaryTags: ['Vegetarian', 'High-Protein'],
    allergens: ['milk'],
    health: { calories: 97, protein: 9, fiber: 0, fat: 5, sugar: 3.6, sodium: 36 },
  },
]

export const sampleDemoInventory: InventoryItem[] = [
  {
    id: 'demo-1',
    name: 'Chickpeas In Water',
    brand: 'Tesco',
    categories: ['chickpeas', 'canned-legumes', 'plant-based-foods'],
    quantity: 3,
    unit: 'tins',
    zone: 'Cupboard',
    expiresOn: '',
    barcode: '5051399182506',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 121, protein: 5.7, fiber: 4.3, fat: 1.8, sugar: 0.7, sodium: 240 },
  },
  {
    id: 'demo-2',
    name: 'Greek Style Yogurt',
    brand: 'Arla',
    categories: ['dairies', 'yogurts'],
    quantity: 2,
    unit: 'pots',
    zone: 'Fridge',
    expiresOn: '',
    barcode: '5000159484695',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'High-Protein'],
    allergens: ['milk'],
    health: { calories: 97, protein: 9.8, fiber: 0, fat: 5.0, sugar: 3.8, sodium: 36 },
  },
  {
    id: 'demo-3',
    name: 'Frozen Mixed Vegetables',
    brand: 'Birds Eye',
    categories: ['frozen-foods', 'vegetables'],
    quantity: 2,
    unit: 'bags',
    zone: 'Freezer',
    expiresOn: '',
    barcode: '5000112548167',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 65, protein: 3.7, fiber: 4.5, fat: 0.5, sugar: 4.2, sodium: 38 },
  },
  {
    id: 'demo-4',
    name: 'Black Beans',
    brand: 'Napolina',
    categories: ['beans', 'canned-legumes'],
    quantity: 2,
    unit: 'tins',
    zone: 'Cupboard',
    expiresOn: '',
    barcode: '80042556',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 91, protein: 6.0, fiber: 6.5, fat: 0.5, sugar: 0.5, sodium: 210 },
  },
  {
    id: 'demo-5',
    name: 'Red Lentils',
    brand: 'East End',
    categories: ['lentils', 'pulses'],
    quantity: 1,
    unit: 'bag',
    zone: 'Cupboard',
    expiresOn: '',
    barcode: '5017689003777',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 332, protein: 24, fiber: 11, fat: 1.8, sugar: 2.0, sodium: 24 },
  },
  {
    id: 'demo-6',
    name: 'Coconut Milk',
    brand: 'Blue Dragon',
    categories: ['coconut-milks', 'asian-foods'],
    quantity: 2,
    unit: 'tins',
    zone: 'Cupboard',
    expiresOn: '',
    barcode: '5010338200824',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 181, protein: 1.6, fiber: 0.7, fat: 18, sugar: 2.0, sodium: 15 },
  },
  {
    id: 'demo-7',
    name: 'Spinach',
    brand: 'Tesco',
    categories: ['leaf-vegetables', 'fresh-foods'],
    quantity: 1,
    unit: 'bag',
    zone: 'Fridge',
    expiresOn: '',
    barcode: '5057753897246',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 23, protein: 2.9, fiber: 2.2, fat: 0.4, sugar: 0.4, sodium: 79 },
  },
  {
    id: 'demo-8',
    name: 'Chicken Breast Fillets',
    brand: 'Tesco',
    categories: ['chicken', 'fresh-foods'],
    quantity: 1,
    unit: 'pack',
    zone: 'Fridge',
    expiresOn: '',
    barcode: '5059697065415',
    source: 'barcode',
    dietaryTags: ['Gluten-Free', 'High-Protein'],
    allergens: [],
    health: { calories: 106, protein: 24, fiber: 0, fat: 1.4, sugar: 0, sodium: 70 },
  },
  {
    id: 'demo-9',
    name: 'Rice',
    brand: 'Tilda',
    categories: ['rices'],
    quantity: 1,
    unit: 'bag',
    zone: 'Cupboard',
    expiresOn: '',
    barcode: '5011157016870',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 350, protein: 7.0, fiber: 1.0, fat: 0.8, sugar: 0.2, sodium: 5 },
  },
  {
    id: 'demo-10',
    name: 'Salmon Fillets',
    brand: 'Tesco',
    categories: ['fish', 'fresh-foods'],
    quantity: 2,
    unit: 'fillets',
    zone: 'Fridge',
    expiresOn: '',
    barcode: '5059697932410',
    source: 'barcode',
    dietaryTags: ['Pescatarian', 'Gluten-Free', 'High-Protein'],
    allergens: ['fish'],
    health: { calories: 208, protein: 20, fiber: 0, fat: 13, sugar: 0, sodium: 59 },
  },
  {
    id: 'demo-11',
    name: 'Potatoes',
    brand: 'Tesco',
    categories: ['tubers', 'fresh-foods'],
    quantity: 1,
    unit: 'bag',
    zone: 'Cupboard',
    expiresOn: '',
    barcode: '5057753018382',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 77, protein: 2.0, fiber: 2.2, fat: 0.1, sugar: 0.8, sodium: 6 },
  },
  {
    id: 'demo-12',
    name: 'Broccoli Florets',
    brand: 'Birds Eye',
    categories: ['frozen-foods', 'broccoli'],
    quantity: 1,
    unit: 'bag',
    zone: 'Freezer',
    expiresOn: '',
    barcode: '5000112633924',
    source: 'barcode',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 34, protein: 2.8, fiber: 2.6, fat: 0.4, sugar: 1.7, sodium: 33 },
  },
]

const starterFamily: FamilyMember[] = [
  {
    id: 'f-1',
    name: 'Alex',
    dietProfile: 'Vegan',
    eatsFish: false,
    dietaryNeeds: ['Nut-Free'] as DietaryTag[],
    avoidIngredients: 'walnuts, peanuts',
  },
  {
    id: 'f-2',
    name: 'Sam',
    dietProfile: 'Omnivore',
    eatsFish: false,
    dietaryNeeds: ['High-Protein'] as DietaryTag[],
    avoidIngredients: '',
  },
]

export const sampleDemoFamily: FamilyMember[] = [
  {
    id: 'demo-family-1',
    name: 'Stephen',
    dietProfile: 'Omnivore',
    eatsFish: false,
    dietaryNeeds: [],
    avoidIngredients: '',
  },
  {
    id: 'demo-family-2',
    name: 'Guest',
    dietProfile: 'Omnivore',
    eatsFish: false,
    dietaryNeeds: ['Nut-Free'],
    avoidIngredients: 'walnuts, peanuts',
  },
]

export const defaultState: AppState = {
  inventory: starterInventory,
  family: starterFamily,
  householdNeeds: ['Nut-Free'],
  cookedMeals: {},
  shoppingChecked: {},
}

export const recipeLibrary: Recipe[] = [
  {
    id: 'r-1',
    title: 'Smoky Chickpea Traybake',
    description: 'Roasted chickpeas and vegetables with paprika, lemon, and herbs.',
    servings: 4,
    ingredients: ['chickpeas', 'mixed vegetables', 'olive oil', 'paprika', 'lemon'],
    steps: [
      'Heat the oven to 220C and drain the chickpeas well.',
      'Toss the chickpeas and mixed vegetables with olive oil, paprika, and a pinch of salt.',
      'Spread everything on a tray and roast for 25 to 30 minutes until crisp at the edges.',
      'Finish with lemon juice and serve with flatbreads or rice.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Nut-Free'],
    allergens: [],
    cookTime: 30,
    zoneFocus: ['Cupboard', 'Freezer'],
    nutrition: { calories: 430, protein: 18, fiber: 13, carbs: 48, fat: 14, sodium: 320 },
    healthHighlights: ['High fibre', 'Plant-based protein', 'Good freezer use'],
  },
  {
    id: 'r-2',
    title: 'Herby Yogurt Chicken Bowls',
    description: 'Chicken bowls with yogurt dressing, grains, and crunchy veg.',
    servings: 4,
    ingredients: ['chicken breast', 'greek yogurt', 'rice', 'cucumber', 'spinach'],
    steps: [
      'Cook the rice according to the packet instructions.',
      'Season and pan-cook the chicken until browned and cooked through, then slice.',
      'Stir chopped herbs into the yogurt with lemon juice and a pinch of salt.',
      'Layer rice, spinach, cucumber, and chicken into bowls, then spoon over the yogurt dressing.',
    ],
    dietaryTags: ['Gluten-Free', 'High-Protein', 'Nut-Free'],
    allergens: ['milk'],
    cookTime: 35,
    zoneFocus: ['Fridge', 'Cupboard'],
    nutrition: { calories: 520, protein: 39, fiber: 6, carbs: 42, fat: 18, sodium: 410 },
    healthHighlights: ['High protein', 'Balanced carbs', 'Great for packed lunches'],
  },
  {
    id: 'r-3',
    title: 'Freezer Veg Stir-Fry',
    description: 'A quick stir-fry built around freezer vegetables and pantry sauces.',
    servings: 4,
    ingredients: ['mixed vegetables', 'soy sauce', 'rice noodles', 'garlic', 'tofu'],
    steps: [
      'Soak or cook the rice noodles following the packet instructions.',
      'Fry the tofu in a hot pan until golden, then add garlic and the frozen vegetables.',
      'Stir in soy sauce and a splash of water to coat everything evenly.',
      'Toss through the noodles and cook for another minute before serving.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free'],
    allergens: ['soy'],
    cookTime: 20,
    zoneFocus: ['Freezer', 'Cupboard'],
    nutrition: { calories: 455, protein: 21, fiber: 8, carbs: 56, fat: 14, sodium: 620 },
    healthHighlights: ['Fast weeknight meal', 'Uses freezer staples', 'Good vegetable density'],
  },
  {
    id: 'r-4',
    title: 'Lentil Cottage Pie',
    description: 'Comforting lentil pie with mashed potato topping and hidden vegetables.',
    servings: 4,
    ingredients: ['lentils', 'potatoes', 'carrots', 'peas', 'vegetable stock'],
    steps: [
      'Boil the potatoes until tender, then mash until smooth.',
      'Simmer lentils with chopped carrots, peas, and vegetable stock until thickened.',
      'Transfer the lentil filling to an oven dish and spread the mash over the top.',
      'Bake until the top is golden and the filling is bubbling.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Nut-Free'],
    allergens: ['celery'],
    cookTime: 55,
    zoneFocus: ['Cupboard', 'Freezer', 'Fridge'],
    nutrition: { calories: 470, protein: 19, fiber: 15, carbs: 63, fat: 12, sodium: 360 },
    healthHighlights: ['High fibre', 'Family-friendly', 'Good batch cook'],
  },
  {
    id: 'r-5',
    title: 'Salmon, Greens and New Potatoes',
    description: 'A lighter dinner with omega-3 rich salmon and green vegetables.',
    servings: 4,
    ingredients: ['salmon', 'potatoes', 'broccoli', 'peas', 'lemon'],
    steps: [
      'Boil the potatoes until tender and steam the broccoli and peas.',
      'Roast or pan-fry the salmon until just cooked through.',
      'Season the vegetables lightly and squeeze lemon over the salmon.',
      'Serve the salmon with potatoes and greens on the side.',
    ],
    dietaryTags: ['Pescatarian', 'Gluten-Free', 'High-Protein', 'Nut-Free'],
    allergens: ['fish'],
    cookTime: 28,
    zoneFocus: ['Fridge', 'Freezer'],
    nutrition: { calories: 510, protein: 37, fiber: 9, carbs: 35, fat: 24, sodium: 280 },
    healthHighlights: ['Omega-3 fats', 'High protein', 'Lower sodium'],
  },
  {
    id: 'r-6',
    title: 'Black Bean Chili',
    description: 'Hearty bean chili with tomatoes, peppers, and warming spices.',
    servings: 4,
    ingredients: ['black beans', 'tomatoes', 'peppers', 'onion', 'cumin'],
    steps: [
      'Cook the onion and peppers in a large pan until softened.',
      'Add cumin and any extra spices, then stir for 30 seconds.',
      'Add tomatoes and black beans and simmer until rich and thick.',
      'Serve with rice, baked potatoes, or tortilla chips.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Nut-Free'],
    allergens: [],
    cookTime: 40,
    zoneFocus: ['Cupboard', 'Fridge'],
    nutrition: { calories: 445, protein: 17, fiber: 16, carbs: 58, fat: 11, sodium: 300 },
    healthHighlights: ['High fibre', 'Budget-friendly', 'Great for leftovers'],
  },
  {
    id: 'r-7',
    title: 'Turkey Meatball Orzo Bake',
    description: 'Protein-forward baked orzo with meatballs, tomato, and spinach.',
    servings: 4,
    ingredients: ['turkey mince', 'orzo', 'tomatoes', 'spinach', 'mozzarella'],
    steps: [
      'Shape the turkey mince into small meatballs and brown them in a pan.',
      'Stir orzo, tomatoes, and a splash of stock into an oven dish.',
      'Add the meatballs and spinach, then top with mozzarella.',
      'Bake until the orzo is tender and the cheese is bubbling.',
    ],
    dietaryTags: ['Nut-Free'],
    allergens: ['milk', 'gluten'],
    cookTime: 45,
    zoneFocus: ['Fridge', 'Cupboard'],
    nutrition: { calories: 560, protein: 34, fiber: 5, carbs: 49, fat: 24, sodium: 540 },
    healthHighlights: ['High protein', 'Oven-to-table', 'Crowd-pleasing'],
  },
  {
    id: 'r-8',
    title: 'Coconut Red Lentil Curry',
    description: 'Creamy lentil curry with spinach and fragrant spices.',
    servings: 4,
    ingredients: ['red lentils', 'coconut milk', 'spinach', 'onion', 'curry paste'],
    steps: [
      'Cook the onion until soft, then stir in the curry paste.',
      'Add red lentils and coconut milk with enough water or stock to simmer.',
      'Cook until the lentils are tender and the sauce has thickened.',
      'Stir through the spinach just before serving.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Nut-Free'],
    allergens: [],
    cookTime: 32,
    zoneFocus: ['Cupboard', 'Fridge'],
    nutrition: { calories: 485, protein: 20, fiber: 12, carbs: 51, fat: 19, sodium: 340 },
    healthHighlights: ['Iron-rich greens', 'High fibre', 'Plant-based dinner'],
  },
  {
    id: 'r-9',
    title: 'Sheet-Pan Sausage and Vegetables',
    description: 'Roasted sausages with colourful vegetables for a simple dinner.',
    servings: 4,
    ingredients: ['sausages', 'potatoes', 'peppers', 'broccoli', 'red onion'],
    steps: [
      'Heat the oven to 220C and chop the vegetables into bite-sized pieces.',
      'Toss the vegetables and sausages with a little oil on a large tray.',
      'Roast for 35 to 40 minutes, turning once, until everything is cooked and browned.',
      'Serve straight from the tray with mustard or a green salad.',
    ],
    dietaryTags: ['Nut-Free'],
    allergens: [],
    cookTime: 38,
    zoneFocus: ['Fridge', 'Freezer'],
    nutrition: { calories: 590, protein: 24, fiber: 8, carbs: 39, fat: 36, sodium: 760 },
    healthHighlights: ['Simple prep', 'Balanced plate', 'Flexible vegetables'],
  },
  {
    id: 'r-10',
    title: 'Yogurt Berry Breakfast Pots',
    description: 'Make-ahead breakfast pots with yogurt, oats, berries, and seeds.',
    servings: 4,
    ingredients: ['greek yogurt', 'berries', 'oats', 'chia seeds', 'honey'],
    steps: [
      'Stir the oats and chia seeds into the yogurt.',
      'Layer the yogurt mixture into jars or bowls with berries.',
      'Drizzle over honey and chill for at least 30 minutes.',
      'Serve cold as a quick breakfast or snack.',
    ],
    dietaryTags: ['Vegetarian', 'High-Protein', 'Nut-Free'],
    allergens: ['milk', 'gluten'],
    cookTime: 10,
    zoneFocus: ['Fridge', 'Cupboard', 'Freezer'],
    nutrition: { calories: 320, protein: 18, fiber: 7, carbs: 36, fat: 10, sodium: 90 },
    healthHighlights: ['Breakfast prep', 'Protein rich', 'Supports satiety'],
  },
]
