import type { CachedProduct } from './types'

// Extend this curated list over time with the barcodes your household scans often.
export const starterProductCache: Record<string, CachedProduct> = {
  '5051399182506': {
    barcode: '5051399182506',
    name: 'Chickpeas In Water',
    brand: 'Tesco',
    categories: ['chickpeas', 'canned-legumes', 'plant-based-foods'],
    unit: 'tins',
    zone: 'Cupboard',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 121, protein: 5.7, fiber: 4.3, fat: 1.8, sugar: 0.7, sodium: 240 },
  },
  '5000159484695': {
    barcode: '5000159484695',
    name: 'Greek Style Yogurt',
    brand: 'Arla',
    categories: ['dairies', 'yogurts'],
    unit: 'pots',
    zone: 'Fridge',
    dietaryTags: ['Vegetarian', 'High-Protein'],
    allergens: ['milk'],
    health: { calories: 97, protein: 9.8, fiber: 0, fat: 5, sugar: 3.8, sodium: 36 },
  },
  '5000112548167': {
    barcode: '5000112548167',
    name: 'Frozen Mixed Vegetables',
    brand: 'Birds Eye',
    categories: ['frozen-foods', 'vegetables'],
    unit: 'bags',
    zone: 'Freezer',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 65, protein: 3.7, fiber: 4.5, fat: 0.5, sugar: 4.2, sodium: 38 },
  },
  '80042556': {
    barcode: '80042556',
    name: 'Black Beans',
    brand: 'Napolina',
    categories: ['beans', 'canned-legumes'],
    unit: 'tins',
    zone: 'Cupboard',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 91, protein: 6, fiber: 6.5, fat: 0.5, sugar: 0.5, sodium: 210 },
  },
  '5017689003777': {
    barcode: '5017689003777',
    name: 'Red Lentils',
    brand: 'East End',
    categories: ['lentils', 'pulses'],
    unit: 'bag',
    zone: 'Cupboard',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 332, protein: 24, fiber: 11, fat: 1.8, sugar: 2, sodium: 24 },
  },
  '5010338200824': {
    barcode: '5010338200824',
    name: 'Coconut Milk',
    brand: 'Blue Dragon',
    categories: ['coconut-milks', 'asian-foods'],
    unit: 'tins',
    zone: 'Cupboard',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 181, protein: 1.6, fiber: 0.7, fat: 18, sugar: 2, sodium: 15 },
  },
  '5057753897246': {
    barcode: '5057753897246',
    name: 'Spinach',
    brand: 'Tesco',
    categories: ['leaf-vegetables', 'fresh-foods'],
    unit: 'bag',
    zone: 'Fridge',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 23, protein: 2.9, fiber: 2.2, fat: 0.4, sugar: 0.4, sodium: 79 },
  },
  '5059697065415': {
    barcode: '5059697065415',
    name: 'Chicken Breast Fillets',
    brand: 'Tesco',
    categories: ['chicken', 'fresh-foods'],
    unit: 'pack',
    zone: 'Fridge',
    dietaryTags: ['Gluten-Free', 'High-Protein'],
    allergens: [],
    health: { calories: 106, protein: 24, fiber: 0, fat: 1.4, sugar: 0, sodium: 70 },
  },
  '5011157016870': {
    barcode: '5011157016870',
    name: 'Rice',
    brand: 'Tilda',
    categories: ['rices'],
    unit: 'bag',
    zone: 'Cupboard',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 350, protein: 7, fiber: 1, fat: 0.8, sugar: 0.2, sodium: 5 },
  },
  '5059697932410': {
    barcode: '5059697932410',
    name: 'Salmon Fillets',
    brand: 'Tesco',
    categories: ['fish', 'fresh-foods'],
    unit: 'fillets',
    zone: 'Fridge',
    dietaryTags: ['Pescatarian', 'Gluten-Free', 'High-Protein'],
    allergens: ['fish'],
    health: { calories: 208, protein: 20, fiber: 0, fat: 13, sugar: 0, sodium: 59 },
  },
  '5057753018382': {
    barcode: '5057753018382',
    name: 'Potatoes',
    brand: 'Tesco',
    categories: ['tubers', 'fresh-foods'],
    unit: 'bag',
    zone: 'Cupboard',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 77, protein: 2, fiber: 2.2, fat: 0.1, sugar: 0.8, sodium: 6 },
  },
  '5000112633924': {
    barcode: '5000112633924',
    name: 'Broccoli Florets',
    brand: 'Birds Eye',
    categories: ['frozen-foods', 'broccoli'],
    unit: 'bag',
    zone: 'Freezer',
    dietaryTags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    allergens: [],
    health: { calories: 34, protein: 2.8, fiber: 2.6, fat: 0.4, sugar: 1.7, sodium: 33 },
  },
}

export function getStarterCachedProduct(barcode: string) {
  return starterProductCache[barcode] ?? null
}
